export { default as HeroImage} from "./hero/hero1.jpg";
export { default as BurgerImage} from "./burger/burger.png";
export { default as CupCakeImage} from "./cupcake/cupcake.png";
export { default as FriesImage} from "./fries/fries.png";
export { default as SandWichImage} from "./sandwich/sandwich.png";
export { default as SpaghettiImage} from "./spaghetti/spaghetti.png";
export { default as PizzaImage} from "./pizza/pizza.png";
export { default as WomanBurgerImage} from "./burger-women/woman-holding-burger.jpg";
export { default as BrandLogo} from "./logo/brand-logo.png";
